# Generated by Django 3.2.16 on 2023-02-06 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_mastersheet'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mastersheet',
        ),
    ]
